package de.lncrna.classification.util;

public enum PropertyKeys {
	FASTA_FILE_LOCATION, 
	FASTA_DOWNLOAD_URL,
	DISTANCE_FILE_LOCATION,
	DISTANCE_CALCULATION_NEXT_RECORD,
	DISTANCE_CALCULATION_THREAD_COUNT,
	PAIRWISE_SEQUENCE_ALIGNER_TYPE,
	GAP_OPEN_PENALTY,
	GAP_CLOSE_PENALTY, 
	DISTANCE_CALCULATION_WAITING_TIME;
}
